version: '3.8'
 
services:
app:
 container_name: weather
 image: weather
 restart: always
 build: .
 ports:
 - "3000:3000"
 links:
  mongodb:
    image: mongo:5.0
    volumes:
      - ./mongo/data:/data/db
    ports:
      - 8007:27017
    container_name: mymongo


